### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by twinik** [twinik/codersraces#2]
- [x] Mejorar entradas a las carreras (que no llegue por parametro, asi no se puede recargar)
- [x] Seguir mejorando los detalles de las carreras
- [x] Mejorar la vista cuando termina una carrera
- [x] Alinear tabla en perfil
- [x] Traer el lenguaje preferido en el perfil (el que mayor carreras tenga, si hay empate, el ultimo)
- [x] Poder entrar a los perfiles de los usuarios desde leaderboard
- [x] Modo oscuro a desplegable de lenguajes y sidebar en mobile
- [x] Que en mobile no se pueda darle a jugar
- [x] Cuestiones de SEO
